# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

-Master
pool:
    VmImage:'ubuntu-latest'
steps:
 -task:
   MavenAuthenticate@0
   inputs:
     MavenService Connection: yourmavenserviceconnection
     mavenpomfile:path/to/your/pom.xml
     option:'-xmx3072m'
  -task:maven@3
    inputs:
      mavenpomfile:'path/to/your/pom.xml'
      goals:'clean package'
      option:'-xmx3072m'